import Foundation

/// Türkiye'deki üniversite adları için arama servisi.
/// Kaynak: YÖK Atlas (https://yokatlas.yok.gov.tr/universite.php). Alfabetik sıra, kelime başı büyük.
struct UniversiteDataService {
    private static let tr = Locale(identifier: "tr_TR")

    /// Kelimelerin sadece ilk harfi büyük (Türkçe uyumlu).
    private static func kelimeBasiBuyuk(_ s: String) -> String {
        s.components(separatedBy: " ").map { word in
            let lower = word.lowercased(with: tr)
            guard let first = lower.first else { return word }
            return String(first).uppercased(with: tr) + lower.dropFirst()
        }.joined(separator: " ")
    }

    /// Ham liste (büyük harf); alfabetik sıra ve "Diğer" eklenerek title case döner.
    private static let hamListe: [String] = [
        "ABDULLAH GÜL ÜNİVERSİTESİ",
        "ACIBADEM MEHMET ALİ AYDINLAR ÜNİVERSİTESİ",
        "ADANA ALPARSLAN TÜRKEŞ BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ",
        "ADIYAMAN ÜNİVERSİTESİ",
        "AFYON KOCATEPE ÜNİVERSİTESİ",
        "AFYONKARAHİSAR SAĞLIK BİLİMLERİ ÜNİVERSİTESİ",
        "AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ",
        "AKDENİZ ÜNİVERSİTESİ",
        "AKSARAY ÜNİVERSİTESİ",
        "ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ",
        "ALANYA ÜNİVERSİTESİ",
        "ALTINBAŞ ÜNİVERSİTESİ",
        "AMASYA ÜNİVERSİTESİ",
        "ANADOLU ÜNİVERSİTESİ",
        "ANKARA BİLİM ÜNİVERSİTESİ",
        "ANKARA ETİMESGUT ÜNİVERSİTESİ",
        "ANKARA HACI BAYRAM VELİ ÜNİVERSİTESİ",
        "ANKARA MEDİPOL ÜNİVERSİTESİ",
        "ANKARA MÜZİK VE GÜZEL SANATLAR ÜNİVERSİTESİ",
        "ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ",
        "ANKARA ÜNİVERSİTESİ",
        "ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ",
        "ANTALYA BELEK ÜNİVERSİTESİ",
        "ANTALYA BİLİM ÜNİVERSİTESİ",
        "ARDAHAN ÜNİVERSİTESİ",
        "ARTVİN ÇORUH ÜNİVERSİTESİ",
        "ATAŞEHİR ADIGÜZEL MESLEK YÜKSEKOKULU",
        "ATATÜRK ÜNİVERSİTESİ",
        "ATILIM ÜNİVERSİTESİ",
        "AVRASYA ÜNİVERSİTESİ",
        "AYDIN ADNAN MENDERES ÜNİVERSİTESİ",
        "BAHÇEŞEHİR ÜNİVERSİTESİ",
        "BALIKESİR ÜNİVERSİTESİ",
        "BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ",
        "BARTIN ÜNİVERSİTESİ",
        "BAŞKENT ÜNİVERSİTESİ",
        "BATMAN ÜNİVERSİTESİ",
        "BAYBURT ÜNİVERSİTESİ",
        "BEYKENT ÜNİVERSİTESİ",
        "BEYKOZ ÜNİVERSİTESİ",
        "BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ",
        "BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ",
        "BİNGÖL ÜNİVERSİTESİ",
        "BİRUNİ ÜNİVERSİTESİ",
        "BİTLİS EREN ÜNİVERSİTESİ",
        "BOĞAZİÇİ ÜNİVERSİTESİ",
        "BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ",
        "BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ",
        "BURSA TEKNİK ÜNİVERSİTESİ",
        "BURSA ULUDAĞ ÜNİVERSİTESİ",
        "ÇAĞ ÜNİVERSİTESİ",
        "ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ",
        "ÇANKAYA ÜNİVERSİTESİ",
        "ÇANKIRI KARATEKİN ÜNİVERSİTESİ",
        "ÇUKUROVA ÜNİVERSİTESİ",
        "DEMİROĞLU BİLİM ÜNİVERSİTESİ",
        "DİCLE ÜNİVERSİTESİ",
        "DOĞUŞ ÜNİVERSİTESİ",
        "DOKUZ EYLÜL ÜNİVERSİTESİ",
        "DÜZCE ÜNİVERSİTESİ",
        "EGE ÜNİVERSİTESİ",
        "ERCİYES ÜNİVERSİTESİ",
        "ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ",
        "ERZURUM TEKNİK ÜNİVERSİTESİ",
        "ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ",
        "ESKİŞEHİR TEKNİK ÜNİVERSİTESİ",
        "FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ",
        "FENERBAHÇE ÜNİVERSİTESİ",
        "FIRAT ÜNİVERSİTESİ",
        "GALATASARAY ÜNİVERSİTESİ",
        "GAZİ ÜNİVERSİTESİ",
        "GAZİANTEP İSLAM BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ",
        "GAZİANTEP ÜNİVERSİTESİ",
        "GEBZE TEKNİK ÜNİVERSİTESİ",
        "GİRESUN ÜNİVERSİTESİ",
        "GÜMÜŞHANE ÜNİVERSİTESİ",
        "HACETTEPE ÜNİVERSİTESİ",
        "HAKKARİ ÜNİVERSİTESİ",
        "HALİÇ ÜNİVERSİTESİ",
        "HARRAN ÜNİVERSİTESİ",
        "HASAN KALYONCU ÜNİVERSİTESİ",
        "HATAY MUSTAFA KEMAL ÜNİVERSİTESİ",
        "HİTİT ÜNİVERSİTESİ",
        "IĞDIR ÜNİVERSİTESİ",
        "ISPARTA UYGULAMALI BİLİMLER ÜNİVERSİTESİ",
        "IŞIK ÜNİVERSİTESİ",
        "İBN HALDUN ÜNİVERSİTESİ",
        "İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ",
        "İNÖNÜ ÜNİVERSİTESİ",
        "İSKENDERUN TEKNİK ÜNİVERSİTESİ",
        "İSTANBUL 29 MAYIS ÜNİVERSİTESİ",
        "İSTANBUL AREL ÜNİVERSİTESİ",
        "İSTANBUL ATLAS ÜNİVERSİTESİ",
        "İSTANBUL AYDIN ÜNİVERSİTESİ",
        "İSTANBUL BEYKENT ÜNİVERSİTESİ",
        "İSTANBUL BİLGİ ÜNİVERSİTESİ",
        "İSTANBUL ESENYURT ÜNİVERSİTESİ",
        "İSTANBUL GALATA ÜNİVERSİTESİ",
        "İSTANBUL GEDİK ÜNİVERSİTESİ",
        "İSTANBUL GELİŞİM ÜNİVERSİTESİ",
        "İSTANBUL KENT ÜNİVERSİTESİ",
        "İSTANBUL KÜLTÜR ÜNİVERSİTESİ",
        "İSTANBUL MEDENİYET ÜNİVERSİTESİ",
        "İSTANBUL MEDİPOL ÜNİVERSİTESİ",
        "İSTANBUL NİŞANTAŞI ÜNİVERSİTESİ",
        "İSTANBUL OKAN ÜNİVERSİTESİ",
        "İSTANBUL RUMELİ ÜNİVERSİTESİ",
        "İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ",
        "İSTANBUL SAĞLIK VE SOSYAL BİLİMLER MESLEK YÜKSEKOKULU",
        "İSTANBUL SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ",
        "İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU",
        "İSTANBUL TEKNİK ÜNİVERSİTESİ",
        "İSTANBUL TİCARET ÜNİVERSİTESİ",
        "İSTANBUL TOPKAPI ÜNİVERSİTESİ",
        "İSTANBUL ÜNİVERSİTESİ",
        "İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA",
        "İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ",
        "İSTİNYE ÜNİVERSİTESİ",
        "İZMİR BAKIRÇAY ÜNİVERSİTESİ",
        "İZMİR DEMOKRASİ ÜNİVERSİTESİ",
        "İZMİR EKONOMİ ÜNİVERSİTESİ",
        "İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ",
        "İZMİR KAVRAM MESLEK YÜKSEKOKULU",
        "İZMİR TINAZTEPE ÜNİVERSİTESİ",
        "İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ",
        "KADİR HAS ÜNİVERSİTESİ",
        "KAFKAS ÜNİVERSİTESİ",
        "KAHRAMANMARAŞ İSTİKLAL ÜNİVERSİTESİ",
        "KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ",
        "KAPADOKYA ÜNİVERSİTESİ",
        "KARABÜK ÜNİVERSİTESİ",
        "KARADENİZ TEKNİK ÜNİVERSİTESİ",
        "KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ",
        "KASTAMONU ÜNİVERSİTESİ",
        "KAYSERİ ÜNİVERSİTESİ",
        "KIRIKKALE ÜNİVERSİTESİ",
        "KIRKLARELİ ÜNİVERSİTESİ",
        "KIRŞEHİR AHİ EVRAN ÜNİVERSİTESİ",
        "KİLİS 7 ARALIK ÜNİVERSİTESİ",
        "KOCAELİ SAĞLIK VE TEKNOLOJİ ÜNİVERSİTESİ",
        "KOCAELİ ÜNİVERSİTESİ",
        "KOÇ ÜNİVERSİTESİ",
        "KONYA GIDA VE TARIM ÜNİVERSİTESİ",
        "KONYA TEKNİK ÜNİVERSİTESİ",
        "KTO KARATAY ÜNİVERSİTESİ",
        "KÜTAHYA DUMLUPINAR ÜNİVERSİTESİ",
        "KÜTAHYA SAĞLIK BİLİMLERİ ÜNİVERSİTESİ",
        "LOKMAN HEKİM ÜNİVERSİTESİ",
        "MALATYA TURGUT ÖZAL ÜNİVERSİTESİ",
        "MALTEPE ÜNİVERSİTESİ",
        "MANİSA CELÂL BAYAR ÜNİVERSİTESİ",
        "MARDİN ARTUKLU ÜNİVERSİTESİ",
        "MARMARA ÜNİVERSİTESİ",
        "MEF ÜNİVERSİTESİ",
        "MERSİN ÜNİVERSİTESİ",
        "MİLLİ SAVUNMA ÜNİVERSİTESİ",
        "MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ",
        "MUDANYA ÜNİVERSİTESİ",
        "MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ",
        "MUNZUR ÜNİVERSİTESİ",
        "MUŞ ALPARSLAN ÜNİVERSİTESİ",
        "NECMETTİN ERBAKAN ÜNİVERSİTESİ",
        "NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ",
        "NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ",
        "NUH NACİ YAZGAN ÜNİVERSİTESİ",
        "ONDOKUZ MAYIS ÜNİVERSİTESİ",
        "ORDU ÜNİVERSİTESİ",
        "ORTA DOĞU TEKNİK ÜNİVERSİTESİ",
        "OSMANİYE KORKUT ATA ÜNİVERSİTESİ",
        "OSTİM TEKNİK ÜNİVERSİTESİ",
        "ÖZYEĞİN ÜNİVERSİTESİ",
        "PAMUKKALE ÜNİVERSİTESİ",
        "PİRİ REİS ÜNİVERSİTESİ",
        "POLİS AKADEMİSİ",
        "RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ",
        "SABANCI ÜNİVERSİTESİ",
        "SAĞLIK BİLİMLERİ ÜNİVERSİTESİ",
        "SAKARYA UYGULAMALI BİLİMLER ÜNİVERSİTESİ",
        "SAKARYA ÜNİVERSİTESİ",
        "SAMSUN ÜNİVERSİTESİ",
        "SANKO ÜNİVERSİTESİ",
        "SELÇUK ÜNİVERSİTESİ",
        "SİİRT ÜNİVERSİTESİ",
        "SİNOP ÜNİVERSİTESİ",
        "SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ",
        "SİVAS CUMHURİYET ÜNİVERSİTESİ",
        "SÜLEYMAN DEMİREL ÜNİVERSİTESİ",
        "ŞIRNAK ÜNİVERSİTESİ",
        "TARSUS ÜNİVERSİTESİ",
        "TED ÜNİVERSİTESİ",
        "TEKİRDAĞ NAMIK KEMAL ÜNİVERSİTESİ",
        "TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ",
        "TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ",
        "TOROS ÜNİVERSİTESİ",
        "TRABZON ÜNİVERSİTESİ",
        "TRAKYA ÜNİVERSİTESİ",
        "TÜRK HAVA KURUMU ÜNİVERSİTESİ",
        "TÜRK-ALMAN ÜNİVERSİTESİ",
        "TÜRK-JAPON BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ",
        "UFUK ÜNİVERSİTESİ",
        "UŞAK ÜNİVERSİTESİ",
        "ÜSKÜDAR ÜNİVERSİTESİ",
        "VAN YÜZÜNCÜ YIL ÜNİVERSİTESİ",
        "YALOVA ÜNİVERSİTESİ",
        "YAŞAR ÜNİVERSİTESİ",
        "YEDİTEPE ÜNİVERSİTESİ",
        "YILDIZ TEKNİK ÜNİVERSİTESİ",
        "YOZGAT BOZOK ÜNİVERSİTESİ",
        "YÜKSEK İHTİSAS ÜNİVERSİTESİ",
        "ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ",
        "DİĞER"
    ]

    /// Alfabetik sırada, kelime başı büyük liste (Türkçe sıralama + "Diğer").
    static var universiteler: [String] {
        hamListe.sorted { $0.localizedCompare($1) == .orderedAscending }.map { kelimeBasiBuyuk($0) }
    }

    /// Kullanıcı yazdıkça eşleşen öneriler; eşleşme yoksa boş dizi (manuel yazmaya devam eder).
    static func searchUniversiteler(query: String, limit: Int = 12) -> [String] {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count >= 2 else { return [] }

        let lowerQuery = trimmed.lowercased(with: tr)
        let list = universiteler

        let filtered = list.filter { uni in
            uni.lowercased(with: tr).contains(lowerQuery)
        }

        return Array(filtered.prefix(limit))
    }
}
